---
###############################################################################
# Ubuntu 16.04 require this
##############################################################################
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no
  vars_prompt:
  - name: "sshKey"
    prompt: "/home/ubuntu/.ssh/id_rsa"
    default: "/home/st/.ssh/github-personal"
