---
###############################################################################
# Ubuntu 16.04 require this
##############################################################################
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: no
  vars_prompt:
  - name: "sshKey"
    prompt: ""
    default: ""
